FROM node:20

WORKDIR /app

COPY backend/package*.json ./
RUN npm install

COPY backend .

RUN npm install -g ts-node-dev
RUN npm install fastify
RUN npm install prisma

CMD npx prisma migrate deploy && npm run dev